import{a as g,S as f,i as w}from"./assets/vendor-u8rapaCG.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&y(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function y(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const L="46278003-3664944736e49f9bfa5b8ba34",b="https://pixabay.com/api/";async function p(e,r=1){try{return(await g.get(`${b}`,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(o){throw o}}let u;function h(e){const r=document.querySelector(".gallery");r.innerHTML+=e.map(o=>`
    <a href="${o.largeImageURL}" class="gallery-item">
      <img src="${o.webformatURL}" alt="${o.tags}" />
      <div class="info">
        <p>Likes: ${o.likes}</p>
        <p>Views: ${o.views}</p>
        <p>Comments: ${o.comments}</p>
        <p>Downloads: ${o.downloads}</p>
      </div>
    </a>
  `).join(""),u?u.refresh():u=new f(".gallery a")}function a(e){w.error({title:"Error",message:e})}function m(){const e=document.querySelector(".loader");e.style.display="block"}function i(){const e=document.querySelector(".loader");e.style.display="none"}const q=document.querySelector(".form"),S=document.querySelector(".input");document.querySelector(".loader");const v=document.querySelector(".gallery"),c=document.querySelector(".load-more");let n=1,l="";new f(".gallery a");q.addEventListener("submit",async e=>{if(e.preventDefault(),l=S.value.trim(),l===""){a("Please enter a search query");return}n=1,v.innerHTML="",c.style.display="none",m();try{const r=await p(l,n);i(),r.hits.length===0?a("Sorry, there are no images matching your search query. Please try again!"):(h(r.hits),c.style.display="block")}catch{i(),a("Failed to fetch images. Please try again later.")}});c.addEventListener("click",async()=>{n+=1,m();try{const e=await p(l,n);i(),h(e.hits),(e.hits.length<15||n*15>=e.totalHits)&&(c.style.display="none",a("We're sorry, but you've reached the end of search results."));const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{i(),a("Failed to fetch images. Please try again later.")}});
//# sourceMappingURL=index.js.map
